#KM-34/feature quote page
wavecrestweb/kenworthy-machine pull request #23
Opened 2024-04-30 20:50 UTC by avinashi10

## Description
This PR adds a responsive 'request a quote' page with a submittable form. Note: This page's form intentionally does not include the additional icons and subheading seen in the Figma design as that allowed me to easily reuse the form component the home page.

## Related Tickets & Documents
Closes #KM-34

## Acceptance Criteria

- [x] All fields must validate inputs (email format for 'Email', required fields for 'Name' and 'Email'). Display errors if validation fails.
- [x] Form sends data with a loading indicator when 'Submit' is clicked. Prevent multiple submissions.
- [x] Show a confirmation message or screen upon successful form submission.
- [x] Ensure the form and all its components adjust properly across devices, with the VStack layout activating on tablet and smaller screens.

## What type of PR is this? (check all applicable)

|     | Type                       |
| --- | -------------------------- |
| ✓ | :sparkles: New feature     |
|  ✓ | 🎨 Style                   |
|     | :hammer: Refactoring       |
|     | 🔥 Performance Improvements|
|     | :bug: Bug fix              |
|     | :100: Add tests            |
|     | :link: Update dependencies |
|     | :scroll: Docs              |

## Mobile & Desktop Screenshots/Recordings
#### Laptop: 
![Screenshot 2024-04-30 at 1 42 14 PM](https://github.com/wavecrestweb/kenworthy-machine/assets/115492619/6e698236-9401-4a21-bf90-8e94efdc6ed6)

#### Tablet: 
![Screenshot 2024-04-30 at 1 39 51 PM](https://github.com/wavecrestweb/kenworthy-machine/assets/115492619/9e558e22-b263-4f03-8570-59f5732cc3db)

#### Mobile:
![Screenshot 2024-04-30 at 1 41 00 PM](https://github.com/wavecrestweb/kenworthy-machine/assets/115492619/839211d8-2a38-4352-89e9-40978cda4ab0)

## What I learned
I practiced setting up the TinaCMS connection again, which operated a little differently when I was passing some the CMS content as props and some needed to be used directly in the component. 

## Testing steps
1. `git switch KM-34/feature-quote-page`
2. `npm i`
3. Create a `.env` file with the following variables:
```
EMAIL_TO= #test with any gmail account you have access to
EMAIL_USER= #test with any gmail account you have access to
EMAIL_PASSWORD= #this password needs to be specifically generated for use here by first turning on 2FA at [myaccount.google.com](https://myaccount.google.com/) and going the 'Security' section and then going to [myaccount.google.com/apppasswords](https://myaccount.google.com/apppasswords)
```
4. `npm run dev`
5. Go to localhost:3000/admin and click 'request a quote' in the header
6. Fill out the form with sample data and submit.
7. Verify that the form submits, and email is received, and that the successful submit message is shown.
8. Verify that the layout adjusts in smaller screen sizes.

## Added to documentation?

|     | Type                       |
| --- | -------------------------- |
|     | 📜 README.md    |
|     | 🙅 no documentation needed    |

## What gif best describes this PR?
  ![gif name](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcWw3azdobXY4ZjFqdnVncDU4emJveDhvNHNudXozY3R2MXJlcW00byZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/2GN4OAIdsMDv10jAVn/giphy.gif)

2024-05-14 04:05 UTC, alibacova requested changes
Yay, last page is pretty much done! Great job, Archaa! There is some things that you need to fix with TinaCMS and form placeholders. I also left a few comments regarding styling, but overall everything looks good.

2024-05-14 04:05 UTC, alibacova commented on tina/config.ts
> +import QuotePageForm from "@/app/components/QuotePage/QuotePageForm";
```suggestion

```

2024-05-14 04:05 UTC, alibacova commented on app/components/QuotePage/QuotePageForm.tsx
> +            placeholder="Share additional information or questions you have. Our team will personally connect with you about this quote."
```suggestion
            placeholder={field3Placeholder || "Share additional information or questions you have. Our team will personally connect with you about this quote."}
```

2024-05-14 04:05 UTC, alibacova commented on content/pages/request_quote.md
> +    field3Placeholder: |
I believe you decided to hardcode the "Email" field placeholder, so field2Placeholder actually should be "Industry type", and field3Placeholder is for the "Share additional info..." text block. It took me a bit to figure out why "Industry Type" placeholder didn't appear anywhere on the form and when I tried to change it in TinaCMS, it's didn't work either lol

2024-05-14 04:05 UTC, alibacova commented on app/(routes)/request-quote/page.tsx
> +  return <QuotePage {...result} />;
I'm getting Typescript error here:
```
Type '{ data: PageQuery; errors?: { message: string; locations: { line: number; column: number; }[]; path: string[]; }[] | undefined; variables: Exact<{ relativePath: string; }>; query: string; }' is not assignable to type '{ data: PageQuery; variables: { relativePath: string; }; query: string; }'.
  The types of 'data.page' are incompatible between these types.
    Type '{ __typename: "PageHome"; id: string; _sys: { __typename?: "SystemInfo" | undefined; filename: string; basename: string; breadcrumbs: string[]; path: string; relativePath: string; extension: string; }; blocks?: ({ ...; } | ... 5 more ... | null)[] | ... 1 more ... | undefined; } | { ...; } | { ...; } | { ...; }' is not assignable to type '{ blocks: (PageRequestQuoteBlocksQuotePageForm | PageRequestQuoteBlocksQuotePageMessage)[]; }'.
      Type '{ __typename: "PageHome"; id: string; _sys: { __typename?: "SystemInfo" | undefined; filename: string; basename: string; breadcrumbs: string[]; path: string; relativePath: string; extension: string; }; blocks?: ({ ...; } | ... 5 more ... | null)[] | ... 1 more ... | undefined; }' is not assignable to type '{ blocks: (PageRequestQuoteBlocksQuotePageForm | PageRequestQuoteBlocksQuotePageMessage)[]; }'.
        Types of property 'blocks' are incompatible.
          Type '({ __typename: "PageHomeBlocksHero"; image?: string | null | undefined; heading?: string | null | undefined; } | { __typename: "PageHomeBlocksValues"; backgroundImage?: string | null | undefined; title?: string | ... 1 more ... | undefined; quality1?: { ...; } | ... 1 more ... | undefined; quality2?: { ...; } | ... ...' is not assignable to type '(PageRequestQuoteBlocksQuotePageForm | PageRequestQuoteBlocksQuotePageMessage)[]'.
            Type 'undefined' is not assignable to type '(PageRequestQuoteBlocksQuotePageForm | PageRequestQuoteBlocksQuotePageMessage)[]'.
```

2024-05-14 04:05 UTC, alibacova commented on app/components/QuotePage/QuotePageForm.tsx
> +        {formTitle || "Request a Quote"}
There's also a subheading/second line that says "or send us a question." It looks like it's for this form only.

2024-05-14 04:05 UTC, alibacova commented on app/components/QuotePage/QuotePageForm.tsx
> +import { FaRegClipboard, FaRegEnvelope, FaRegHandshake } from "react-icons/fa6";
```suggestion

```

2024-05-14 04:05 UTC, alibacova commented on app/components/QuotePage/QuotePageForm.tsx
> +          Submit
Just noticed that this doesn't use TinaCMS data. The same is happening for the Home page and Machines page forms.

2024-05-14 04:05 UTC, alibacova commented on app/components/QuotePage/QuotePage.tsx
> +      <Stack
On the wireframes there is no space around the form, it's stretched from the top to bottom. I think it's okay to leave it as is if it's a headache to change that.

2024-05-14 04:05 UTC, alibacova commented on app/components/QuotePage/QuotePage.tsx
> +            <QuotePageForm
It looks like you could've reused the HomePageForm here unless I missed something.

2024-05-14 04:05 UTC, alibacova commented on app/components/QuotePage/QuotePage.tsx
> +        spacing={16}
This needs to be adjusted for mobile and tablets

2024-05-14 04:05 UTC, alibacova commented on app/components/QuotePage/QuotePage.tsx
> +        >
I'm not sure which screen size you've used for the mobile view (looks like iPhone 12 Pro?), but when I select "iPhone 14 Pro Max" in Chrome, the message body stretches all the way:
<img width="496" alt="Screen Shot 2024-05-13 at 8 46 54 PM" src="https://github.com/wavecrestweb/kenworthy-machine/assets/109827834/854fd585-85c2-479c-8e43-5f4998f6eaf9">
It looks fine for pretty much all the other mobile screens available in Chrome devtools, so I think it's okay if you decide to leave it as is.

2024-05-14 16:14 UTC, avinashi10 commented on content/pages/request_quote.md
> +    field2Placeholder: Email
```suggestion
    field2Placeholder: Industry Type
```

2024-05-14 16:14 UTC, avinashi10 commented on content/pages/request_quote.md
> +    field3Placeholder: |
```suggestion
    field3Placeholder: Share additional information or questions you have. Our team will personally connect with you about this quote.
```

2024-05-30 16:07 UTC, avinashi10 commented on app/components/QuotePage/QuotePageForm.tsx
> +        {formTitle || "Request a Quote"}
I ended up reusing the HomeQuoteForm like you suggested. Since that doesn't have 'or send us a question', for sake of simplicity I won't add it

2024-05-30 18:24 UTC, BrettEastman approved these changes
Everything works perfectly! All of the i's dotted and t's crossed. Really great work, Archaa. Merge it!

2024-05-30 20:18 UTC, merged